const user = '6671e008deb85bed4791bfcc';

const tmdbImageBaseUrl = 'https://image.tmdb.org/t/p/original';
export const data = [
  {
    _id: '6671e008deb85bed4791bf01',
    title: 'Inside Out 2',
    backdropUrl: tmdbImageBaseUrl + '/qjoX7hl721FOiyeHsDkeQ6rFVLl.jpg',
    posterUrl: tmdbImageBaseUrl + '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    releaseDate: '2024-06-11',
    description:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust.",
    rating: 7.297,
    budget: 150000000,
    revenue: 875000000,
    runtime: 102,
    videoUrl: 'https://youtu.be/L4DrolmDxmw',
    user: user,
    genres: ['Comedy', 'Drama', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf02',
    title: 'Hit Man',
    backdropUrl: tmdbImageBaseUrl + '/nv6F6tz7r61DUhE7zgHwLJFcTYp.jpg',
    posterUrl: tmdbImageBaseUrl + '/5BfcYFhRVlgWLFo4SCkQNsIWzyy.jpg',
    releaseDate: '2024-05-16',
    description:
      'A mild-mannered professor moonlighting as a fake hit man in police stings ignites a chain reaction of trouble when he falls for a potential client.',
    rating: 6.945,
    budget: 30000000,
    revenue: 120000000,
    runtime: 118,
    videoUrl: 'https://youtu.be/9a7C7Bxsm90',
    user,
    genres: ['Action', 'Comedy', 'Drama'],
  },
  {
    _id: '6671e008deb85bed4791bf03',
    title: 'Ultraman: Rising',
    backdropUrl: tmdbImageBaseUrl + '/SI22DaQXIfDvLrNBHGpSVShrsC.jpg',
    posterUrl: tmdbImageBaseUrl + '/j886YEkIUsiImY53px5VHKD4lRa.jpg',
    releaseDate: '2024-06-14',
    description: 'With Tokyo under attack from kaiju, Ultraman discovers his greatest challenge isn’t fighting giant monsters - it’s raising one.',
    rating: 6.7,
    budget: 50000000,
    revenue: 86000000,
    runtime: 112,
    videoUrl: 'https://youtu.be/TwXgOMDONK8',
    user,
    genres: ['Action', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf04',
    title: 'I Saw the TV Glow',
    backdropUrl: tmdbImageBaseUrl + '/sNBnCmF1ueoERa4uW5kh929KkRO.jpg',
    posterUrl: tmdbImageBaseUrl + '/hS4GYkYpN1rfl4GIxyc02sCyfAj.jpg',
    releaseDate: '2024-05-03',
    description:
      'Teenager Owen is just trying to make it through life in the suburbs when his classmate introduces him to a mysterious late-night TV show — a vision of a supernatural world beneath their own.',
    rating: 6.6,
    budget: 25000000,
    revenue: 65000000,
    runtime: 105,
    videoUrl: 'https://youtu.be/kymDzCgPwj0',
    user,
    genres: ['Drama', 'Horror'],
  },
  {
    _id: '6671e008deb85bed4791bf05',
    title: 'Bad Boys: Ride or Die',
    backdropUrl: tmdbImageBaseUrl + '/ga4OLm4qLxPqKLMzjJlqHxVjst3.jpg',
    posterUrl: tmdbImageBaseUrl + '/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg',
    releaseDate: '2024-06-05',
    description: 'After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.',
    rating: 7,
    budget: 80000000,
    revenue: 230000000,
    runtime: 130,
    videoUrl: 'https://youtu.be/uWLNl_KQCAU',
    user,
    genres: ['Action', 'Comedy'],
  },
  {
    _id: '6671e008deb85bed4791bf06',
    title: 'Under Paris',
    backdropUrl: tmdbImageBaseUrl + '/xQkotnzv12fm9FF29if1cBLsyU3.jpg',
    posterUrl: tmdbImageBaseUrl + '/qZPLK5ktRKa3CL4sKRZtj8UlPYc.jpg',
    releaseDate: '2024-06-05',
    description: 'In the Summer of 2024, Paris is hosting the World Triathlon Championships on the Seine for the first time.',
    rating: 5.791,
    budget: 60000000,
    revenue: 145000000,
    runtime: 115,
    videoUrl: 'https://youtu.be/jnCefPQIH98',
    user,
    genres: ['Action', 'Drama', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf07',
    title: 'The Fall Guy',
    backdropUrl: tmdbImageBaseUrl + '/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg',
    posterUrl: tmdbImageBaseUrl + '/aBkqu7EddWK7qmY4grL4I6edx2h.jpg',
    releaseDate: '2024-04-24',
    description:
      'Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.',
    rating: 7.261,
    budget: 35000000,
    revenue: 105000000,
    runtime: 122,
    videoUrl: 'https://youtu.be/EySdVK0NK1Y',
    user,
    genres: ['Action', 'Drama'],
  },
  {
    _id: '6671e008deb85bed4791bf08',
    title: 'Godzilla x Kong: The New Empire',
    backdropUrl: tmdbImageBaseUrl + '/jvPMJ2zM92jfXxVEFsqP1MMrLaO.jpg',
    posterUrl: tmdbImageBaseUrl + '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    releaseDate: '2024-03-27',
    description:
      'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
    rating: 7.218,
    budget: 200000000,
    revenue: 800000000,
    runtime: 135,
    videoUrl: 'https://youtu.be/XeDbyVODQ5M',
    user,
    genres: ['Action', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf09',
    title: 'Dune: Part Two',
    backdropUrl: tmdbImageBaseUrl + '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    posterUrl: tmdbImageBaseUrl + '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    releaseDate: '2024-02-27',
    description:
      'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    rating: 8.166,
    budget: 180000000,
    revenue: 900000000,
    runtime: 155,
    videoUrl: 'https://youtu.be/U2Qp5pL3ovA',
    user,
    genres: ['Action', 'Drama', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf10',
    title: 'Furiosa: A Mad Max Saga',
    backdropUrl: tmdbImageBaseUrl + '/7v4gev91nO3i66Zzygh9jplu9UI.jpg',
    posterUrl: tmdbImageBaseUrl + '/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
    releaseDate: '2024-05-22',
    description:
      'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus.',
    rating: 7.636,
    budget: 160000000,
    revenue: 750000000,
    runtime: 145,
    videoUrl: 'https://youtu.be/LYV3001u574',
    user,
    genres: ['Action', 'Drama', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf11',
    title: 'Mysteries of the Terracotta Warriors',
    backdropUrl: tmdbImageBaseUrl + '/Ge1rNZGqZafXrQTJP84klXhxkH.jpg',
    posterUrl: tmdbImageBaseUrl + '/snl9dddlnu2yKXXix2ua7G8UWoe.jpg',
    releaseDate: '2024-06-11',
    description:
      "Thousands of terracotta warriors guarded the first Chinese emperor's tomb. This is their story, told through archaeological evidence and reenactments.",
    rating: 6.4,
    budget: 20000000,
    revenue: 55000000,
    runtime: 98,
    videoUrl: 'https://youtu.be/9Msxc8AiTrc',
    user,
    genres: ['Action', 'Drama', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf12',
    title: 'Civil War',
    backdropUrl: tmdbImageBaseUrl + '/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg',
    posterUrl: tmdbImageBaseUrl + '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
    releaseDate: '2024-04-10',
    description:
      'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
    rating: 7.012,
    budget: 40000000,
    revenue: 95000000,
    runtime: 124,
    videoUrl: 'https://youtu.be/c2G18nIVpNE',
    user,
    genres: ['Drama'],
  },
  {
    _id: '6671e008deb85bed4791bf13',
    title: 'Deadpool & Wolverine',
    backdropUrl: tmdbImageBaseUrl + '/hzr7GhCoWTeQQMKDR6LXhN8x9fs.jpg',
    posterUrl: tmdbImageBaseUrl + '/jbwYaoYWZwxtPP76AZnfYKQjCEB.jpg',
    releaseDate: '2024-07-24',
    description:
      'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an even more reluctant Wolverine.',
    rating: 0,
    budget: 75000000,
    revenue: 280000000,
    runtime: 132,
    videoUrl: 'https://youtu.be/73_1biulkYk',
    user,
    genres: ['Action', 'Comedy', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf14',
    title: 'Winnie-the-Pooh: Blood and Honey 2',
    backdropUrl: tmdbImageBaseUrl + '/p4INKu77iuTG1o1a5N3Y9vqeEGq.jpg',
    posterUrl: tmdbImageBaseUrl + '/2sADrLwMQof6yYmrJRSa04tFZuS.jpg',
    releaseDate: '2024-03-26',
    description:
      'Five months following the murders, Christopher Robin tries returning to his regular life while dealing with his PTSD. Deep within the 100-Acre-Wood, their lives endangered after their existence is revealed.',
    rating: 6.442,
    budget: 60000000,
    revenue: 160000000,
    runtime: 110,
    videoUrl: 'https://youtu.be/dgIlZOv4M-c',
    user,
    genres: ['Drama', 'Horror'],
  },
  {
    _id: '6671e008deb85bed4791bf15',
    title: 'Inside Out',
    backdropUrl: tmdbImageBaseUrl + '/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg',
    posterUrl: tmdbImageBaseUrl + '/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
    releaseDate: '2015-06-09',
    description:
      'From an adventurous balloon ride above the clouds to a monster-filled metropolis, Academy Award®-winning director Pete Docter (“Monsters, Inc.,” “Up”) has taken audiences to unique and imaginative places.',
    rating: 7.915,
    budget: 175000000,
    revenue: 857600000,
    runtime: 95,
    videoUrl: 'https://youtu.be/1HFv47QHWJU',
    user,
    genres: ['Animation', 'Adventure', 'Comedy'],
  },
  {
    _id: '6671e008deb85bed4791bf16',
    title: 'Godzilla Minus One',
    backdropUrl: tmdbImageBaseUrl + '/fY3lD0jM5AoHJMunjGWqJ0hRteI.jpg',
    posterUrl: tmdbImageBaseUrl + '/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg',
    releaseDate: '2023-11-03',
    description:
      'In postwar Japan, Godzilla brings new devastation to an already scorched landscape. With no military intervention or government help in sight, the survivors must join together in the face of despair and fight back against an unrelenting horror.',
    rating: 7.614,
    budget: 120000000,
    revenue: 460000000,
    runtime: 118,
    videoUrl: 'https://youtu.be/nAYKaslCXPc',
    user,
    genres: ['Action', 'Drama', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf17',
    title: 'The Watchers',
    backdropUrl: tmdbImageBaseUrl + '/oZDRuGHhe5uY8wBqFJcJZT9kdvJ.jpg',
    posterUrl: tmdbImageBaseUrl + '/vZVEUPychdvZLrTNwWErr9xZFmu.jpg',
    releaseDate: '2024-06-06',
    description:
      'A young artist gets stranded in an extensive, immaculate forest in western Ireland, where, after finding shelter, she becomes trapped alongside three strangers, stalked by mysterious creatures each night.',
    rating: 5.882,
    budget: 28000000,
    revenue: 85000000,
    runtime: 107,
    videoUrl: 'https://youtu.be/dYo91Fq9tKY',
    user,
    genres: ['Horror', 'Mystery', 'Thriller'],
  },
  {
    _id: '6671e008deb85bed4791bf18',
    title: 'Kingdom of the Planet of the Apes',
    backdropUrl: tmdbImageBaseUrl + '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
    posterUrl: tmdbImageBaseUrl + '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
    releaseDate: '2024-05-08',
    description:
      "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows.",
    rating: 6.818,
    budget: 150000000,
    revenue: 620000000,
    runtime: 126,
    videoUrl: 'https://youtu.be/Kdr5oedn7q8',
    user,
    genres: ['Action', 'Drama', 'Sci-Fi'],
  },
  {
    _id: '6671e008deb85bed4791bf19',
    title: 'The Strangers: Chapter 1',
    backdropUrl: tmdbImageBaseUrl + '/6LksoR7reQ45gQRik0zhrHmcpZw.jpg',
    posterUrl: tmdbImageBaseUrl + '/qyT2xw9FBxHlNXQYsuNCu8T7Rbo.jpg',
    releaseDate: '2024-05-15',
    description:
      'After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.',
    rating: 5.551,
    budget: 25000000,
    revenue: 78000000,
    runtime: 98,
    videoUrl: 'https://youtu.be/3pZUQmZdOi4',
    user,
    genres: ['Horror', 'Mystery', 'Thriller'],
  },
  {
    _id: '6671e008deb85bed4791bf20',
    title: 'Challengers',
    backdropUrl: tmdbImageBaseUrl + '/504GSaoxBA5nLlcMsJfjzLZEKUp.jpg',
    posterUrl: tmdbImageBaseUrl + '/H6vke7zGiuLsz4v4RPeReb9rsv.jpg',
    releaseDate: '2024-04-18',
    description:
      'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a top player. But when Art is offered a chance to play in the US Open, Tashi must confront her own past and the choices she made to get him there.',
    rating: 6.4,
    budget: 35000000,
    revenue: 105000000,
    runtime: 112,
    videoUrl: 'https://youtu.be/-2N3hmRmwHQ',
    user,
    genres: ['Drama'],
  },
];
